a = input('Digite algo: ')
print('O tipo primitivo do valor digitado é ', type(a))
print('Só tem espaços? ', a.isspace())
print('é um número? ', a.isnumeric())
print('É alfabético ?', a.isalpha())
print('É alfanumérico ?', a.isalnum())
print('Está em MAIÚSCULO? ', a.isupper())
print('Está em minúsculo? ', a.islower())
print('Está capitalizada? ', a.istitle())
