#FAÇA UM PROGRAMA QUE LEIA UM NÚMERO INTEIRO QUALQUER E MOSTRE NA TELA A SUA TABUADA
n = int(input('Informe um número: '))
print('-' * 12)
print('{:2} X 1 = {:2}'.format(n,n*1))
print('{:2} X 2 = {:2}'.format(n,n*2))
print('{:2} X 3 = {:2}'.format(n,n*3))
print('{:2} X 4 = {:2}'.format(n,n*4))
print('{:2} X 5 = {:2}'.format(n,n*5))
print('{:2} X 6 = {:2}'.format(n,n*6))
print('{:2} X 7 = {:2}'.format(n,n*7))
print('{:2} X 8 = {:2}'.format(n,n*8))
print('{:2} X 9 = {:2}'.format(n,n*9))
print('{:2} X 10 = {:2}'.format(n,n*10))
print('-' * 12)